# Generated by Django 3.1.7 on 2024-01-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0002_auto_20230925_1103'),
        ('eProc_Archiving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='arch_CompanyGrpUser',
            fields=[
                ('company_grp_user_guid', models.CharField(db_column='COMPANY_GUID', max_length=32, primary_key=True, serialize=False)),
                ('company_grp_id', models.CharField(db_column='COMPANY_GRP_ID', max_length=20)),
                ('username', models.CharField(db_column='USERNAME', max_length=16)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(db_column='Client', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
            ],
            options={
                'db_table': 'MSS_COMP_CODE_GRP_USER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='arch_CompanyCodeGrp',
            fields=[
                ('company_grp_guid', models.CharField(db_column='COMPANY_GUID', max_length=32, primary_key=True, serialize=False)),
                ('company_grp_id', models.CharField(db_column='COMPANY_GRP_ID', max_length=20)),
                ('company_code_id', models.CharField(db_column='COMPANY_CODE_ID', max_length=20)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(db_column='Client', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
            ],
            options={
                'db_table': 'MSS_COMP_CODE_GRP',
                'managed': True,
            },
        ),
    ]
