# Generated by Django 3.1.7 on 2024-02-14 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc_Configuration', '0002_auto_20230925_1103'),
        ('eProc_Archiving', '0002_arch_companycodegrp_arch_companygrpuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='arch_Country',
            fields=[
                ('country_code', models.CharField(db_column='COUNTRY_CODE', max_length=2, primary_key=True, serialize=False)),
                ('country_name', models.CharField(db_column='COUNTRY_NAME', max_length=100)),
                ('del_ind', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'MMD_COUNTRY',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='arch_OrgClients',
            fields=[
                ('client', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
                ('del_ind', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'MMD_CLIENTS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='arch_UserSearch',
            fields=[
                ('username', models.CharField(db_column='USERNAME', max_length=16)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=40, null=True)),
                ('last_name', models.CharField(db_column='LAST_NAME', max_length=40, null=True)),
                ('map_id', models.CharField(db_column='MAP_ID', max_length=8, primary_key=True, serialize=False)),
                ('client', models.ForeignKey(db_column='CLIENT', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
            ],
            options={
                'db_table': 'MSS_USER_INFO',
                'managed': True,
                'unique_together': {('client', 'username')},
            },
        ),
        migrations.CreateModel(
            name='arch_CountryCompCode',
            fields=[
                ('country_comp_code_guid', models.CharField(db_column='COMPANY_GUID', max_length=32, primary_key=True, serialize=False)),
                ('company_code_id', models.CharField(db_column='COMPANY_CODE_ID', max_length=20)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(db_column='CLIENT', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
                ('country', models.ForeignKey(db_column='COUNTRY', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.country')),
            ],
            options={
                'db_table': 'MSS_COUNTRY_COMP_CODE',
                'managed': True,
                'unique_together': {('client', 'company_code_id')},
            },
        ),
        migrations.CreateModel(
            name='arch_CompanyCode',
            fields=[
                ('company_code_guid', models.CharField(db_column='COMPANY_CODE_GUID', default=True, max_length=32, primary_key=True, serialize=False)),
                ('company_code_id', models.CharField(db_column='COMPANY_CODE_ID', max_length=20)),
                ('company_code_desc', models.CharField(db_column='COMPANY_CODE_DESC', max_length=100)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(db_column='CLIENT', on_delete=django.db.models.deletion.PROTECT, to='eProc_Configuration.orgclients')),
            ],
            options={
                'db_table': 'MMD_CCODES',
                'managed': True,
                'unique_together': {('client', 'company_code_id')},
            },
        ),
    ]
